import colors from "./colors";

const inter = {
  regular: "Inter_400Regular",
  medium: "Inter_500Medium",
  bold: "Inter_700Bold",
};

export default {
  Heading1: {
    fontFamily: "Inter",
    fontSize: 34,
    lineHeight: 48,
    color: colors.textPrimary,
  },
  Heading2: {
    fontFamily: inter.bold,
    fontSize: 28,
    lineHeight: 42,
    color: colors.textPrimary,
  },
  Heading3: {
    fontFamily: inter.bold,
    fontSize: 24,
    lineHeight: 36,
    color: colors.textPrimary,
  },
  Heading4: {
    fontFamily: inter.bold,
    fontSize: 22,
    lineHeight: 32,
    color: colors.textPrimary,
  },
  Heading5: {
    fontFamily: inter.bold,
    fontSize: 20,
    lineHeight: 28,
    color: colors.textPrimary,
  },
  Heading6: {
    fontFamily: inter.bold,
    fontSize: 18,
    lineHeight: 26,
    color: colors.textPrimary,
  },

  BodyLargeRegular: {
    fontFamily: inter.regular,
    fontSize: 16,
    lineHeight: 24,
    color: colors.textPrimary,
  },
  BodyLargeSemibold: {
    fontFamily: inter.medium,
    fontSize: 16,
    lineHeight: 24,
    color: colors.textPrimary,
  },
  BodyLargeBold: {
    fontFamily: inter.bold,
    fontSize: 16,
    lineHeight: 24,
    color: colors.textPrimary,
  },
  BodyLargeItalic: {
    fontFamily: inter.regular,
    fontStyle: "italic",
    fontSize: 16,
    lineHeight: 24,
    color: colors.textPrimary,
  },
  BodyLargeUnderline: {
    fontFamily: inter.regular,
    textDecorationLine: "underline",
    fontSize: 16,
    lineHeight: 24,
    color: colors.textPrimary,
  },
  BodyLargeUnderlineSemibold: {
    fontFamily: inter.medium,
    textDecorationLine: "underline",
    fontSize: 16,
    lineHeight: 24,
    color: colors.textPrimary,
  },
  BodyLargeUnderlineBold: {
    fontFamily: inter.bold,
    textDecorationLine: "underline",
    fontSize: 16,
    lineHeight: 24,
    color: colors.textPrimary,
  },

  BodySmallRegular: {
    fontFamily: inter.regular,
    fontSize: 14,
    lineHeight: 21,
    color: colors.textPrimary,
  },
  BodySmallSemibold: {
    fontFamily: inter.medium,
    fontSize: 14,
    lineHeight: 21,
    color: colors.textPrimary,
  },
  BodySmallBold: {
    fontFamily: inter.bold,
    fontSize: 14,
    lineHeight: 21,
    color: colors.textPrimary,
  },
  BodySmallItalic: {
    fontFamily: inter.regular,
    fontStyle: "italic",
    fontSize: 14,
    lineHeight: 21,
    color: colors.textPrimary,
  },
  BodySmallUnderline: {
    fontFamily: inter.regular,
    textDecorationLine: "underline",
    fontSize: 14,
    lineHeight: 21,
    color: colors.textPrimary,
  },
  BodySmallUnderlineSemibold: {
    fontFamily: inter.medium,
    textDecorationLine: "underline",
    fontSize: 14,
    lineHeight: 21,
    color: colors.textPrimary,
  },
  BodySmallUnderlineBold: {
    fontFamily: inter.bold,
    textDecorationLine: "underline",
    fontSize: 14,
    lineHeight: 21,
    color: colors.textPrimary,
  },

  CaptionLargeRegular: {
    fontFamily: inter.regular,
    fontSize: 12,
    lineHeight: 18,
    color: colors.textPrimary,
  },
  CaptionLargeSemibold: {
    fontFamily: inter.medium,
    fontSize: 12,
    lineHeight: 18,
    color: colors.textPrimary,
  },
  CaptionLargeBold: {
    fontFamily: inter.bold,
    fontSize: 12,
    lineHeight: 18,
    color: colors.textPrimary,
  },
  CaptionLargeItalic: {
    fontFamily: inter.regular,
    fontStyle: "italic",
    fontSize: 12,
    lineHeight: 18,
    color: colors.textPrimary,
  },
  CaptionLargeUnderline: {
    fontFamily: inter.regular,
    textDecorationLine: "underline",
    fontSize: 12,
    lineHeight: 18,
    color: colors.textPrimary,
  },
  CaptionLargeUnderlineSemibold: {
    fontFamily: inter.medium,
    textDecorationLine: "underline",
    fontSize: 12,
    lineHeight: 18,
    color: colors.textPrimary,
  },
  CaptionLargeUnderlineBold: {
    fontFamily: inter.bold,
    textDecorationLine: "underline",
    fontSize: 12,
    lineHeight: 18,
    color: colors.textPrimary,
  },

  CaptionSmallRegular: {
    fontFamily: inter.regular,
    fontSize: 10,
    lineHeight: 15,
    color: colors.textPrimary,
  },
  CaptionSmallSemibold: {
    fontFamily: inter.medium,
    fontSize: 10,
    lineHeight: 15,
    color: colors.textPrimary,
  },
  CaptionSmallBold: {
    fontFamily: inter.bold,
    fontSize: 10,
    lineHeight: 15,
    color: colors.textPrimary,
  },
  CaptionSmallItalic: {
    fontFamily: inter.regular,
    fontStyle: "italic",
    fontSize: 10,
    lineHeight: 15,
    color: colors.textPrimary,
  },
  CaptionSmallUnderline: {
    fontFamily: inter.regular,
    textDecorationLine: "underline",
    fontSize: 10,
    lineHeight: 15,
    color: colors.textPrimary,
  },
  CaptionSmallUnderlineSemibold: {
    fontFamily: inter.medium,
    textDecorationLine: "underline",
    fontSize: 10,
    lineHeight: 15,
    color: colors.textPrimary,
  },
  CaptionSmallUnderlineBold: {
    fontFamily: inter.bold,
    textDecorationLine: "underline",
    fontSize: 10,
    lineHeight: 15,
    color: colors.textPrimary,
  },
};
